esphome:
  name: "terrarium-humidifier"
  friendly_name: "terrarium-humidifier"

esp8266:
  board: d1
  restore_from_flash: true

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: uptime
    name: Uptime Sensor

# Enable logging
logger:

switch:
  - platform: gpio
    name: humidifier
    id: humidifier
    pin:
      number: D2
      inverted: false

time:
  - platform: sntp
    id: sntp_time
    timezone: "Europe/Moscow"
    update_interval: 600s
    on_time_sync:
      then:
        - logger.log: "Synchronized sntp clock"
  - platform: homeassistant
    id: hass_time
    update_interval: 180s
    timezone: "Europe/Moscow"
    on_time_sync:
      then:
        - logger.log: "Synchronized homeassistant clock"
    # ...
    on_time:

      # Cron syntax, trigger every 5 minutes
      - cron: '0 * * * * *'
        then:
          - switch.turn_on: humidifier
      - cron: '15 * * * * *'
        then:
          - switch.turn_off: humidifier

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {} # This spawns an AP with the device name and mac address with no password.

#captive_portal:
