esphome:
  name: polyphonic-alarm
  on_loop:
    then:
      if:
        condition:
          # Same syntax for is_off
          - switch.is_on: alarm_sensor
          - not:
             rtttl.is_playing
        then:
          - rtttl.play: 'MissionImp:d=16,o=6,b=95:32d,32d#,32d,32d#,32d,32d#,32d,32d#,32d,32d,32d#,32e,32f,32f#,32g,g,8p,g,8p,a#,p,c7,p,g,8p,g,8p,f,p,f#,p,g,8p,g,8p,a#,p,c7,p,g,8p,g,8p,f,p,f#,p,a#,g,2d,32p,a#,g,2c#,32p,a#,g,2c,a#5,8c,2p,32p,a#5,g5,2f#,32p,a#5,g5,2f,32p,a#5,g5,2e,d#,8d'

esp32:
  board: lolin_d32
  framework:
    type: arduino

# Enable logging
logger:

switch:
  - platform: template
    name: "Alarm Switch"
    optimistic: true
    id: alarm_sensor
    internal: false

output:
  - platform: ledc
    pin: GPIO18
    inverted: true
    id: rtttl_out

rtttl:
  output: rtttl_out
  on_finished_playback:
    - logger.log: 'Song ended!'

wifi:
  ssid: "dummy"
  password: "dummy_password"

api:
  services:
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'

