esphome:
  name: terratium-relay

  on_loop:
    then:
      lambda: |-
          static unsigned long last_update = 0;
          static unsigned long enabledForTime = 0;
          int iteration = 5000; // every 5 sec
          if((last_update + iteration) < millis()){
             last_update = millis();
             if(id(relay2).state){
               enabledForTime+=iteration;
             }
             else{
               enabledForTime = 0;
             }
             ESP_LOGD("ERM", "Heat relay enabled for: %lu", enabledForTime);
             if(enabledForTime> 1000*60*20){ // 20 min, safety measure
               ESP_LOGD("ERM", "Turning off heat relay");
               id(relay2).turn_off();
               enabledForTime = 0; // avoid confusion when HA turns on relay back
             }
          }

esp8266:
  board: d1

wifi:
  ssid: "dummy"
  password: "dummy_password"

# Enable logging
logger:

# Enable Home Assistant API
api:

switch:
  - platform: gpio
    pin: D2
    name: Relay1
    id: relay1
    inverted: true
  - platform: gpio
    pin: D3
    name: Relay2
    id: relay2
    inverted: true
  - platform: gpio
    pin: D4
    name: Relay3
    id: relay3
    inverted: true
  - platform: gpio
    pin: D5
    name: Relay4
    id: relay4
    inverted: true
