name: Build ESPHome

on:
  - push
  - pull_request

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - came-gates-controller/came-gates-controller.yaml
          - polyphonic-alarm/polyphonic-alarm.yaml
          - terrarium-dimmer/terrarium-dimmer.yaml
          - terrarium-dimmer-v2/terrarium-dimmer-v2.yaml
          - terrarium-humidifier/terrarium-humidifier.yaml
          - cricket-house/cricket-house.yaml
          - terrarium-relay/terrarium-relay.yaml
          - co2-sensor/co2-sensor.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Copy sample settings
        run: |
          cp came-gates-controller/settings.sample.h came-gates-controller/settings.h
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v1.8.0
        with:
          yaml_file: ${{ matrix.file }}
